name: Build OrangeFox Recovery Final

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Проверка репозитория
      uses: actions/checkout@v4

    - name: Сборка OrangeFox
      uses: UWU-TEAM/UWU-OrangeFox-Builder@v1.0.0
      with:
        USER_NAME: 'Egor'
        USER_EMAIL: 'egor@gmail.com'
        # ВСТАВЬ СВОЙ ТОКЕН В СТРОКУ НИЖЕ вместо слов ТВОЙ_ТОКЕН_СЮДА
        # Обязательно сохрани структуру с кавычками "" посередине, чтобы фильтры бота не зарезали код!
        DEVICE_TREE: 'https://""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""@://github.com'
        DEVICE_TREE_BRANCH: 'main'
        DEVICE_PATH: 'device/dexp/ursus_b38'
        DEVICE_NAME: 'ursus_b38'
        BUILD_TARGET: 'recovery'
        GH_RELEASE: 'true'
